version: '3'
services:
  web:
    build: .
    ports:
    - "4000:4000"
    depends_on:
      - db_pg

  db_pg:
    image: postgres:latest
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: nqueendb